export const ENTITIES = Object.freeze({
    USER: "ADMIN_USER",
    ROLE: "ROLE",
    PERMISSION: "PERMISSION",

    ZONE: "ZONE",
    STATE: "STATE",
    DISTRICT: "DISTRICT",
    BLOCK: "BLOCK",

    CROP: "CROP",
    CROP_STAGE: "CROP-STAGES",
    CROP_RANGE: "CROP-STAGES",
    SENSOR_ALERT: "SENSOR_ALERT",
    CATEGORY: "CATEGORY",

    ADVISORY: "ADVISORY",
    ADVISORY_TYPE: "ADVISORY_TYPE",

    WEATHER: "WEATHER"
});